from typing import Dict, Any
from db_agent.config import CHAT_MODEL_DEPLOYMENT
from db_agent.graph.state import AgentState
from db_agent.client.az_llm import build_agent
from db_agent.schema.pydantic_models import PlannerOutput

async def agent_planner_node(state: AgentState) -> Dict[str, Any]:
    """
    Phase 2: The Brain
    Decides the next action: Query Graph, Run SP, or Finalize.
    FIX: Added Deterministic Logic for Diagnostic Loop to prevent recursion errors.
    """
    print("--- [Node] Agent Planner ---")

    # 1. Circuit Breaker
    loop_count = state.get("loop_count", 0)
    if loop_count >= state.get("max_loops", 25): # Increased default to 25 to match recursion limit
        print("   > Circuit Breaker Triggered (Max Loops Reached)")
        return {"next_action": "FINALIZE"}

    # 2. Context
    intent = state.get("intent_status")
    messages = state["messages"]
    hypotheses = state.get("hypotheses_queue", [])
    confirmed_causes = state.get("confirmed_causes", [])

    # =========================================================================
    # FIX: DETERMINISTIC DIAGNOSTIC LOGIC (Bypasses LLM for Stability)
    # =========================================================================
    if intent == "DIAGNOSTIC":
        # A. If we have hypotheses to test -> DO IT (Don't ask LLM)
        if hypotheses:
            current = hypotheses[0]
            print(f"   > [Diagnostic] Queue has items. Testing: {current}")
            return {
                "next_action": "TEST_HYPOTHESIS",
                "current_hypothesis": current,
                "hypotheses_queue": hypotheses[1:], # POP the queue here
                "tool_params": {} # Params are auto-generated by Executor later
            }
        
        # B. If queue is EMPTY but we have findings -> DONE (Stop the loop)
        if confirmed_causes:
            print("   > [Diagnostic] Queue empty & Findings exist. Finalizing.")
            return {"next_action": "FINALIZE"}
            
        # C. If queue is EMPTY and NO findings -> Start Investigation (Fall through to LLM)
        # The LLM below will trigger "QUERY_KG"
        pass
    # =========================================================================

    # 3. Guardrail: Descriptive/Ambiguous Answer Found
    if (intent == "DESCRIPTIVE" or intent == "AMBIGUOUS") and confirmed_causes:
        print(f"   > Answer found (Intent: {intent}). Auto-Finalizing.")
        return {"next_action": "FINALIZE"}

    # 4. System Prompt
    system_prompt = f"""
    You are the Planner for Sherlock.
    
    CONTEXT:
    - Intent: {intent}
    - Findings: {confirmed_causes}
    
    AVAILABLE TOOLS:
    1. sp_GetAggregatedCost: Returns Cost, FTE, Headcount. 
       Params: ProjectName, CustomerName, Location.
    2. sp_GetDistribution: Returns list of values (e.g. Top 10 Projects).
       Params: ColumnName, TopN.
       
    LIMITATIONS:
    - You ONLY have data for: Cost, FTE, Headcount, and Distribution of categories.
    - You DO NOT have data for: Project Codes, Managers, Start Dates, or Descriptions.
    
    LOGIC RULES:
    [IF Intent = DESCRIPTIVE or AMBIGUOUS]
    - If user provides a specific name (Project/Customer): EXECUTE sp_GetAggregatedCost.
    - If user asks for a list (e.g. "Show projects"): EXECUTE sp_GetDistribution.
    - If user asks for data you DON'T have: output next_action="FINALIZE".
    - NEVER output next_action="QUERY_KG".

    [IF Intent = DIAGNOSTIC]
    - (Note: The testing loop is handled automatically. You only start the process.)
    - IF no hypotheses and no findings: Output next_action="QUERY_KG".
    
    Output strictly as JSON matching PlannerOutput.
    """

    # 5. Run Agent
    last_msg = messages[-1]
    
    # Robust Message Parsing
    if hasattr(last_msg, 'content'):
        user_input = last_msg.content
    elif isinstance(last_msg, (list, tuple)) and len(last_msg) > 1:
        user_input = str(last_msg[1])
    else:
        user_input = str(last_msg)

    agent = build_agent(
        output_type_schema=PlannerOutput,
        system_prompt=system_prompt,
        model_name=CHAT_MODEL_DEPLOYMENT['reasoning'],
    )

    result = await agent.run(user_input)
    decision: PlannerOutput = result.output

    # --- GUARDRAIL: FORCE BLOCK KG ON DESCRIPTIVE ---
    if intent == "DESCRIPTIVE" and decision.next_action == "QUERY_KG":
        print("   > [Guardrail] Blocked QUERY_KG for Descriptive Intent. Finalizing.")
        return {"next_action": "FINALIZE"}

    print(f"   > Decision: {decision.next_action}")
    if decision.tool_name:
        print(f"   > Tool: {decision.tool_name} {decision.tool_params}")

    # 6. Update State
    updates = {
        "next_action": decision.next_action,
        "tool_params": decision.tool_params or {},
    }
    
    if decision.tool_name:
        updates["tool_params"]["tool_name"] = decision.tool_name

    return updates